services:
  backend: 
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: booking_web
    restart: unless-stopped
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - booking-network
    expose:
      - "9000"
  db:
    image: mysql:8.0
    container_name: booking-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: booking_web_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - booking-network
      
  redis:
    image: redis:7
    container_name: booking-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - booking-network

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "8000:80" # dev local
      #- "80:80" # production
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/certs:/etc/nginx/certs
      # - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      # - /etc/letsencrypt/live/api.sky-enterprise.id.vn/fullchain.pem:/etc/nginx/certs/fullchain.pem
      # - /etc/letsencrypt/live/api.sky-enterprise.id.vn/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - backend
    networks:
      - booking-network
volumes:
  dbdata:
networks:
  booking-network:
    driver: bridge